dependencies {
    api "io.reactivex:rxjava:$rxJavaVersion"
    api "org.graceframework:grace-datastore-core:$graceDataVersion"
    api "org.graceframework:grace-datastore-gorm:$graceDataVersion"
    implementation "org.javassist:javassist:$javassistVersion"
    compileOnly("org.hibernate.validator:hibernate-validator:$hibernateValidatorVersion")
    documentation "org.springframework:spring-beans:$springVersion"
    documentation "org.graceframework:grace-async-core:$graceAsyncVersion"
}
